modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/globalista-dev/fastchest_reforged/issues"

[[mods]]
modId="fastchest"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="fastchest_logo.png"
displayURL="https://github.com/globalista-dev/fastchest_reforged"
description='''${mod_description}'''